
if(DB43_INCLUDE_DIR AND DB43_LIBRARY)
  # Already in cache, be silent
  set(DB43_FIND_QUIETLY TRUE) 
endif(DB43_INCLUDE_DIR AND DB43_LIBRARY)

set(DB43_LIBRARY)
set(DB43_INCLUDE_DIR)

FIND_PATH(DB43_INCLUDE_DIR db43/db.h
  /usr/include
  /usr/local/include
)

FIND_LIBRARY(DB43_LIBRARY NAMES db-4.3
  PATHS
  /usr/lib
  /usr/local/lib
)

if(DB43_INCLUDE_DIR AND DB43_LIBRARY)
   MESSAGE( STATUS "db-4.3 found: includes in ${DB43_INCLUDE_DIR}, library in ${DB43_LIBRARY}")
   set(DB43_FOUND TRUE)
else(DB43_INCLUDE_DIR AND DB43_LIBRARY)
   MESSAGE( STATUS "db-4.3 not found")
endif(DB43_INCLUDE_DIR AND DB43_LIBRARY)

MARK_AS_ADVANCED(DB43_INCLUDE_DIR DB43_LIBRARY)