---
name: CI

on:
  push:
    branches:
      - master
      - 0.6.x
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run:  |
          sudo apt-get install cmake
      - name: Build
        run:  |
          mkdir build
          cd build
          cmake -DDEBIAN=1 -DMULTI_SEMANTICS=1 -DCMAKE_VERBOSE_MAKEFILE=TRUE ..
          make
      - name: Test
        run:  |
          cd build
          make test
